edit_uri: ''
extra_css:
- css/extra.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
google_analytics:
- UA-27795084-5
- mkdocs.org
markdown_extensions:
- toc:
    separator: '#'
- admonition
- def_list
- mdx_gh_links:
    repo: mkdocs
    user: mkdocs
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- Theory:
  - Database-transaction:
    - Introduction:
      - Introduction: Theory/Database-transaction/Transaction/index.md
    - Course-ucsd-Lecture-8-Transactions-ACID-2PC-2PL-Serializability:
      - Introduction: Theory/Database-transaction/Course-ucsd-Lecture-8-Transactions-ACID-2PC-2PL-Serializability/index.md
    - ACID:
      - Introduction: Theory/Database-transaction/ACID/index.md
      - Atomicity:
        - Introduction: Theory/Database-transaction/ACID/Atomicity/index.md
      - Consistency(database-systems):
        - Introduction: Theory/Database-transaction/ACID/Consistency(database-systems)/index.md
      - Isolation:
        - Introduction: Theory/Database-transaction/ACID/Isolation/index.md
        - Isolation-level:
          - Introduction: Theory/Database-transaction/ACID/Isolation/Isolation-level/index.md
    - Implementation:
      - Introduction: Theory/Database-transaction/Implementation/index.md
      - Atomic-commit:
        - Introduction: Theory/Database-transaction/Implementation/Atomic-commit/index.md
      - Serializability:
        - Introduction: Theory/Database-transaction/Implementation/Serializability/index.md
  - Concurrency-Control-in-DBMS:
    - Introduction: Theory/Concurrency-Control-in-DBMS/index.md
    - Problem:
      - Introduction: Theory/Concurrency-Control-in-DBMS/Problem/index.md
  - Cursor: Theory/Cursor.md
- SQL:
  - Introduction: SQL/index.md
  - join:
    - "zhihu-\u56FE\u89E3SQL-join":
      - Introduction: "SQL/join/zhihu-\u56FE\u89E3SQL-join/index.md"
  - group-by:
    - Introduction: SQL/group-by/index.md
- Implementation:
  - SQLite:
    - doc:
      - Introduction: Impl/SQLite/doc/index.md
      - Technical-and-Design-Documentation:
        - Architecture-of-SQLite: Impl/SQLite/doc/Technical-and-Design-Documentation/Architecture-of-SQLite.md
        - Virtual-Table-Mechanism-Of-SQLite:
          - Virtual-Table-Mechanism-Of-SQLite: Impl/SQLite/doc/Technical-and-Design-Documentation/Virtual-Table-Mechanism-Of-SQLite/index.md
          - Example-CSV: Impl/SQLite/doc/Technical-and-Design-Documentation/Virtual-Table-Mechanism-Of-SQLite/Example-CSV.md
        - TODO: Impl/SQLite/doc/Technical-and-Design-Documentation/TODO.md
      - Extensions:
        - Run-Time-Loadable-Extensions: Impl/SQLite/doc/Extensions/Run-Time-Loadable-Extensions.md
      - Programming-Interfaces:
        - How-To-Compile-SQLite: Impl/SQLite/doc/Programming-Interfaces/How-To-Compile-SQLite.md
        - Setting-The-Result-Of-An-SQL-Function: Impl/SQLite/doc/Programming-Interfaces/Setting-The-Result-Of-An-SQL-Function.md
  - SQL-compiler:
    - Introduction: Impl/SQL-compiler/index.md
- Expert-Guy-Harrison:
  - Introduction: Expert-Guy-Harrison/index.md
plugins:
- search
repo_url: https://github.com/dengking/DB
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: DB
site_url: https://dengking.github.io/DB
theme:
  name: material
